require ("plugins.lualine")
require ("plugins.bufferline")
require ("plugins.treesitter")
require ("plugins.nvim-tree")
require ("plugins.comments")
require ("plugins.telescope")
require ("plugins.alpha")
require ("plugins.indentline")
require ("plugins.autopairs")
-- require ("plugins.cmp")
require ("plugins.colorizer")
require ("plugins.gitsigns")
require ("plugins.lsp")
--require ("plugins.lspkind")
-- require ("plugins.lsp-install")
-- require ("plugins.nvim-comment")
